# Generated by Django 2.2.16 on 2021-12-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenreTitle',
        ),
    ]
